spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: board-manager-service
          uri: ${BOARD_MANAGER_SERVICE_URL}
          predicates:
            - Path=/board-manager-service/api/**
          filters:
            - RewritePath=/board-manager-service/api/(?<segment>.*),/api/$\{segment}
            - name: RequestLogger
              args:
                format: "Request: {} {}"
        - id: board-manager-websocket
          uri: ${BOARD_MANAGER_WEBSOCKET_URL}
          predicates:
            - Path=/board-manager-websocket/**
          filters:
            - RewritePath=/board-manager-websocket/(?<segment>.*),/$\{segment}
            - name: RequestLogger
              args:
                format: "Request: {} {}"
        - id: tile-manager-service
          uri: ${TILE_MANAGER_SERVICE_URL}
          predicates:
            - Path=/tile-manager-service/api/**
          filters:
            - RewritePath=/tile-manager-service/api/(?<segment>.*),/api/$\{segment}
            - name: RequestLogger
              args:
                format: "Request: {} {}"
        - id: game-service
          uri: ${GAME_SERVICE_URL}
          predicates:
            - Path=/game-service/api/**
          filters:
            - RewritePath=/game-service/api/(?<segment>.*),/api/$\{segment}
            - name: RequestLogger
              args:
                format: "Request: {} {}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
server:
  port: 8085

#Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

#Routes
