spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: board-manager-service
          uri: http://localhost:8080/api/
          predicates:
            - Path=/board-manager-service/api/**
          filters:
            - RewritePath=/board-manager-service/api/(?<segment>.*),/api/$\{segment}
            - name: RequestLogger
              args:
                format: "Request: {} {}"
        - id: board-manager-websocket
          uri: http://localhost:8080/
          predicates:
            - Path=/board-manager-websocket/**
          filters:
            - RewritePath=/board-manager-websocket/(?<segment>.*),/$\{segment}
            - name: RequestLogger
              args:
                format: "Request: {} {}"
        - id: tile-manager-service
          uri: http://localhost:8082/api/
          predicates:
            - Path=/tile-manager-service/api/**
          filters:
            - RewritePath=/tile-manager-service/api/(?<segment>.*),/api/$\{segment}
            - name: RequestLogger
              args:
                format: "Request: {} {}"
        - id: game-service
          uri: http://localhost:8087/api/
          predicates:
            - Path=/game-service/api/**
          filters:
            - RewritePath=/game-service/api/(?<segment>.*),/api/$\{segment}
            - name: RequestLogger
              args:
                format: "Request: {} {}"
        - id: external-services
          uri: http://localhost:8088/api/
          predicates:
            - Path=/external-services/api/**
          filters:
            - RewritePath=/external-services/api/(?<segment>.*),/api/$\{segment}
            - name: RequestLogger
              args:
                format: "Request: {} {}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8086/realms/scrabble
server:
  port: 8085

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

#Routes
